name: Deploy Pages

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Sphinx
      run: |
        sudo apt update
        sudo apt-get install -y doxygen graphviz python3-pip
        pip3 install sphinx sphinx-rtd-theme breathe exhale

    - name: Generate HTML
      run: |
        cd docs
        make html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: build/html
        force_orphan: true
